/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_LOGGER_H_RPCGEN
#define _RPC_LOGGER_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


#define LOGGER_PROG ((rpc_uint)0x20000001)
#define LOGGER_VERS ((rpc_uint)1)

#ifdef __cplusplus
#define LOG_EVENT ((rpc_uint)1)
extern "C" void * log_event_1(char **, CLIENT *);
extern "C" void * log_event_1_svc(char **, struct svc_req *);

#elif __STDC__
#define LOG_EVENT ((rpc_uint)1)
extern  void * log_event_1(char **, CLIENT *);
extern  void * log_event_1_svc(char **, struct svc_req *);

#else /* Old Style C */
#define LOG_EVENT ((rpc_uint)1)
extern  void * log_event_1();
extern  void * log_event_1_svc();
#endif /* Old Style C */

#endif /* !_RPC_LOGGER_H_RPCGEN */
